import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SearchBar from '@/components/SearchBar'
import PlantsFinder from '@/components/PlantsFinder'
import PlantsCare from '@/components/PlantsCare'
import MyPlants from '@/components/MyPlants'
import AddPlants from '@/components/AddPlants'
import EditPlants from '@/components/EditPlants'
import Login from '@/components/Login'
import Signup from '@/components/Signup'
import Styles from "@/styles/myPlants.module.sass";


export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <div>
            <SearchBar/>
            <div className={Styles.box1}>
                <h1 className={Styles.title}>MY PLANTS</h1>
                <button className={Styles.AddButton}>ADD PLANTS</button>
            </div>
            <div className={Styles.plantsShow}>
                <div className={Styles.plants}>
                    <Image src="/ToolPlant1.png" width={234} height={449}></Image>
                    <div className={Styles.captions}>
                        <h1>TOOL A</h1>
                        <p>To take good care of your plants and Toby together.</p>
                        <button className={Styles.editButton}>EDIT</button>
                    </div>
                </div>
                <div className={Styles.plants}>
                    <Image src="/ToolPlant2.png" width={234} height={449}></Image>
                    <div className={Styles.captions}>
                        <h1>TOOL B</h1>
                        <p>To take good care of your plants and Toby together.</p>
                        <button className={Styles.editButton}>EDIT</button>
                    </div>
                </div>
                <div className={Styles.plants}>
                    <Image src="/ToolPlant3.png" width={234} height={449}></Image>
                    <div className={Styles.captions}>
                        <h1>TOOL C</h1>
                        <p>To take good care of your plants and Toby together.</p>
                        <button className={Styles.editButton}>EDIT</button>
                    </div>
                </div>
                <div className={Styles.plants}>
                    <Image src="/ToolPlant4.png" width={234} height={449}></Image>
                    <div className={Styles.captions}>
                        <h1>TOOL D</h1>
                        <p>To take good care of your plants and Toby together.</p>
                        <button className={Styles.editButton}>EDIT</button>
                    </div>
                </div>
            </div>
        </div>
      <div className={styles.foot}>
      <Footer/>
      </div>
      
      
      
    </div>
  )
}
