import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Head from 'next/head'

import styles from '../styles/Home.module.css'

import Styles from "@/styles/AddPlants.module.sass"


export default function Home() {


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
        <div >
            <h1 className={Styles.title}>Add Plants</h1>
            <div className={Styles.forms}>
                <input type="file" placeholder="Upload your image" className={Styles.upload} />
                <input type="text" placeholder="Name" className={Styles.inputs}/>
                <input type="text" placeholder="Description" className={Styles.inputs}/>
                <button className={Styles.button}>Done</button>
            </div>
        </div>


      <div className={styles.foot}>
      <Footer/>
      </div>
      
      
      
    </div>
  )
}
