import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Head from 'next/head'

import styles from '../styles/Home.module.css'
import HomePage from '../components/HomeContents/home'
import SearchBar from '@/components/SearchBar'
import PlantsFinder from '@/components/PlantsFinder'
import PlantsCare from '@/components/PlantsCare'
import MyPlants from '@/components/MyPlants'
import AddPlants from '@/components/AddPlants'
import EditPlants from '@/components/EditPlants'
import { useState } from 'react'

export default function Home() {
  const [pages, setPages] = useState(0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      {
      pages===0 &&
      <HomePage/>
      }
      {
      pages===1 &&
      <PlantsFinder/>
      }
      {
      pages===2 &&
      <PlantsCare/>
      }
      {
      pages===3 &&
      <MyPlants/>
      }
      
      <div className={styles.foot}>
      <Footer/>
      </div>
      
      
      
    </div>
  )
}
