import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Head from 'next/head'

import styles from '../styles/Home.module.css'
import HomePage from '../components/HomeContents/home'

import PlantsFinder from '@/components/PlantsFinder'
import PlantsCare from '@/components/PlantsCare'
import { useState } from 'react'

export default function Home() {
  const [pages, setPages] = useState(0);
  const routeHome = () =>{
    setPages(0);
  }
  const routeFinder = () =>{
    setPages(1);
  }
  const routeCare = () =>{
    setPages(2);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header Home={routeHome} PlantsC={routeCare} PlantsF={routeFinder}/>
      {
        pages===0 &&
        <HomePage/>
      }
      {
        pages===1 &&
        <PlantsFinder/>
      }
      {
        pages===2 &&
        <PlantsCare/>
      }
      
      <Footer/>
      
      
      
      
    </div>
  )
}
