import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Head from 'next/head'

import styles from '../styles/Home.module.css'
import Login from '@/components/Login'


export default function LoginPage() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Login/>
      <div className={styles.foot}>
      <Footer/>
      </div>
      
      
      
    </div>
  )
}
